.github/workflows/release.yml

This is just copied from the terraform-provider-scaffolding-framework example without any changes.

Add a github workflow for goreleaser

---

.github/workflows/test.yml
Makefile
cdp-sdk-go/cdp/config.go
main.go
provider/provider.go
provider/provider_test.go
resources/datalake/resource_aws_datalake.go
resources/environments/resource_aws_credential.go
resources/ml/resource_workspace.go
utils/copyright_test.go
utils/slice.go

I added a github workflow that uses github actions to run the build and the unit and terraform acceptance tests for every pull request. 
The contents of the github workflow mimics the https://github.com/hashicorp/terraform-provider-scaffolding-framework/tree/main/.github/workflows as well as other similar providers from Hashicorp. This seems like a good start for the initial test, but we will add more workflows (especially for releasing later).
In the process I had to: 
- Fix lint errors (1 actual bug)
- Ignore some lint issues
- Add build and lint targets to the Makefile
- Remove deprecated / unused code
- Fix the copy-right header tests on Windows

Add a pre commit test github workflow

---

.goreleaser.yaml
cdp-sdk-go/cdp/auth.go
cdp-sdk-go/cdp/client.go
cdp-sdk-go/cdp/config.go
cdp-sdk-go/cdp/transport.go
cdp-sdk-go/cdp/transport_test.go
provider/provider.go
provider/provider_test.go

I've extended the SDK to be able to accept a custom User-Agent header as well as the header for
x-altus-client-app which is defined in the Java SDK (not sure whether it is used or not). The
user agent header is set to follow the pattern for CDP CLI and Java SDK.
Further, the terraform provider now overrides the user agent from the SDK with a Terraform specific
one. We intend to split the cdp-sdk-go into its own repository so once that happens, the user agent
from the go SDK vs the user agent from the terraform provider should be tracked differently.
"This commit does not contain secrets"
Testing done:
- new unit tests

Set User-Agent and x-altus-client-app headers for the golang SDK

---

cdp-sdk-go/cdp/config_test.go
cdp-sdk-go/cdp/credentials.go
cdp-sdk-go/cdp/credentials_test.go
cdp-sdk-go/cdp/testdata/test-config
cdp-sdk-go/cdp/testdata/test-credentials

Fixed issue caused by config names that have uppercase characters

---

.github/workflows/test.yml
Makefile
docs/resources/environments_aws_environment.md
docs/resources/environments_gcp_credential.md
examples/resources/cdp_environments_aws_environment/resource.tf
examples/resources/cdp_environments_gcp_credential/resource.tf

We disabled running `terraform fmt` on the `examples/` directory since the CI builds did not have terraform in the container / VM image. Now that we are building with github, we can enable that again both for local builds as well as builds for github checks. The only downside is that all local builds will require terraform to be installed.

Run Terraform fmt for examples files during the build

---

cdp-sdk-go/cdp/config_test.go
cdp-sdk-go/cdp/credentials.go
cdp-sdk-go/cdp/credentials_test.go
cdp-sdk-go/cdp/testdata/test-config
cdp-sdk-go/cdp/testdata/test-credentials

* Fixed issue caused by config names that have uppercase characters
* Fixed unit test and add more test cases
We decided to follow the Python CDP CLI semantics for case sensitivity to be compatible between the two tools and least surprises to the end user. Python INI file parsing defaults to case sensitive section names, but case insensitive option names. We do the same in the go SDK.
This commit adds some more unit tests.
---------

Fixed issue caused by config names that have uppercase characters (#37)

---

resources/environments/resource_aws_environment.go

When applying `cdp_environments_aws_environment` with `security_access.default_security_group_ids` and `security_access.security_group_ids_for_knox` set, Terraform eventually terminates with an error, saying that there is a bug in the provider.
Snippet from tf file:
```
resource "cdp_environments_aws_environment" "cdp_env" {
...
security_access = {
default_security_group_ids  = ["sg-01234567890a", "sg-01234567890b", "sg-01234567890c"]
security_group_ids_for_knox =  ["sg-01234567890a", "sg-01234567890b", "sg-01234567890d"]
}
...
}
```
Error produced by Terraform:
```
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to cdp_environments_aws_environment.cdp_env, provider "provider[\"registry.terraform.io/cloudera/cdp\"]" produced an unexpected new value: …
```

cdp_environments_aws_environment overrides security_group_ids_for_knox with default_security_group_ids

---

examples/resources/cdp_dw_aws_cluster/resource.tf
provider/provider.go
provider/provider_test.go
resources/dw/cluster/aws/model_cluster.go
resources/dw/cluster/aws/resource_cluster.go
resources/dw/cluster/aws/resource_cluster_test.go
resources/dw/cluster/aws/schema_cluster.go

This commit adds the basic creation and deletion capabilities
- The model and schema for a data warehouse aws eks cluster creation
- The creation call
- The deletion call
- Unit test coverage for creation and deletion, success and failure scenarios

DWX-18732 Create and delete CDW AWS cluster object

---

cdp-sdk-go/cdp/client.go
cdp-sdk-go/cdp/config.go
cdp-sdk-go/cdp/config_test.go
resources/iam/model_machine_user_resource_role_assignment.go
resources/iam/resource_machine_user_resource_role_assignment.go
resources/iam/resource_machine_user_resource_role_assignment_test.go
resources/iam/resource_machine_user_role_assignment.go
resources/iam/resource_machine_user_role_assignment_test.go
resources/iam/test_common_utils.go

We want to assign a `role` to a `machine user` via the Terraform resource `cdp_iam_machine_user_role_assignment`:
```bash
resource "cdp_iam_machine_user" "provisioning" {
name = "dev-provisioning"
}
resource "cdp_iam_machine_user_role_assignment" "provisioning_environment_admin" {
machine_user = cdp_iam_machine_user.provisioning.name
role                   = "crn:altus:iam:eu-1:altus:role:EnvironmentAdmin"
depends_on = [ cdp_iam_machine_user.provisioning ]
}
````
When applying the changes, Terraform fails with a nil pointer dereference error:
```
cdp_iam_machine_user_role_assignment.provisioning_environment_admin: Creating...
╷
│ Error: Request cancelled
│
│ The plugin6.(*GRPCProvider).ApplyResourceChange request was cancelled.
╵
Stack trace from the terraform-provider-cdp_v0.6.2 plugin: …
```

PR #147: Machine User Role and Resource Role Assignment Fails

---

resources/dw/resource_hive_vw_acc_test.go

The acceptance test will be skipped until the dependent objects - CDW cluster and database catalog - are properly allocated and awaited by their respective tests.

CDPCP-12598 Skip CDW Hive test if env var is not set

---

resources/dw/cluster/aws/model_cluster.go
resources/dw/cluster/aws/model_cluster_test.go
resources/dw/cluster/aws/resource_cluster.go
resources/dw/cluster/aws/resource_cluster_test.go
resources/dw/cluster/aws/schema_cluster.go

This change awaits the data warehouse aws cluster creation to finish and move the cluster to a Running or Error state.

DWX-18776 Wait for dw aws cluster to become ready

---

provider/provider.go
provider/provider_test.go
resources/dw/databasecatalog/model_catalog.go
resources/dw/databasecatalog/model_catalog_test.go
resources/dw/databasecatalog/resource_catalog.go
resources/dw/databasecatalog/resource_catalog_test.go
resources/dw/databasecatalog/schema_catalog.go

Adding creation and deletion options for the data warehouse catalog object type.

DWX-18781 Data warehouse catalog object management

---

resources/dw/virtualwarehouse/hive/model_hive_vw.go
resources/dw/virtualwarehouse/hive/resource_hive_vw.go
resources/dw/virtualwarehouse/hive/resource_hive_vw_acc_test.go
resources/dw/virtualwarehouse/hive/resource_hive_vw_test.go
utils/utils.go
utils/utils_test.go

The timeout and threshold calculation is duplicated in every dw module, it is moved to utils to reduce duplication.

DWX-18764 Move polling utilities to utils

---

cdpacctest/acctest.go
resources/dw/resource_dw_acc_test.go

Cover the dw environment, db catalog and hive virtual warehouse creations and deletions as part of acceptance testing.

Data Warehouse acceptance tests for catalog, hive

---

.terraformrc
Makefile

Newer go installations don't require setting the GOPATH explicitly.
To make managing the GOHOME more flexible the `install-terraformrc` and `check-go` targets have been improved.

Improvement on make install-terraformrc goal

---

.github/workflows/test.yml

The toolchain was upgraded to 1.22, the tests should be running on this version as well.

CDPCP-13607 Add go version 1.22 to test matrix

---

resources/datalake/resource_aws_datalake_test.go

This change temporarily disables the data lake acceptance test environment destroy. This change should be reverted

Fixing e2e tests

---

resources/dw/resource_dw_acc_test.go

Clusters are auto-deleted from the AWS account. To keep them some tags with the proper values must be applied.
This change removes the owner tag, the framework value should be used automatically to keep the resources around.

Fix end to end dw cluster test runs

---

docs/resources/dw_aws_cluster.md
examples/resources/cdp_dw_aws_cluster/resource.tf
resources/dw/cluster/aws/model_cluster.go
resources/dw/cluster/aws/resource_cluster_test.go
resources/dw/cluster/aws/schema_cluster.go
resources/dw/resource_dw_aws_acc_test.go

The enable_private_eks option is added to the AWS DW module. With this parameter the inverting proxy endpoint is set up and the EKS API endpoint will use a private address.

CDPCP-13540 DW New parameter: enable_private_eks

---

resources/dw/resource_dw_aws_acc_test.go
resources/dw/virtualwarehouse/hive/resource_hive_vw_acc_test.go

The data warehouse module does not accept space characters in the tag format, this change replaces the tags. This is needed for successful e2e test runs.

CDPCP-13938 Change tags for hive virtual warehouse tests

---

.github/workflows/test.yml

GH action jobs under the _.github/workflows/test.yml_ are getting triggered even though all the jobs should've been run on the designated PR (since no direct push is allowed to the _main_ branch).
This is not just unnecessary resource usage, but since some jobs can be branch-specific (such as the commit count checker job that can be run only on branches that are not the main) this means these jobs shall fail and would confuse the readers of the repo.

CDPCP-14126 - GH action jobs are getting triggered once a PR is landed on the main even though it is not necessary

---

resources/dw/resource_dw_aws_acc_test.go

Reverts cloudera/terraform-provider-cdp#221
The fix for the DW issue have been resolved and the new version is promoted to development environments. The standalone hive acceptance test was successful. The test should be enabled back.

Revert "CDPCP-14163 - temporarily disable DW acceptance test(s) due to product issue"

---

resources/dw/resource_dw_aws_acc_test.go

During e2e testing the hive warehouse went into a Stopping state from the Starting state. Probably during the 30s of poll time the auto suspend timeout was hit and that prevented us to see the Running state of the entity. The auto suspend timeout will be set to 20 minutes and that should be enough time for a warehouse to start and the check to succeed.

CDPCP-14163 Increase hive auto suspend timeout

---

resources/dw/resource_dw_aws_acc_test.go
resources/dw/virtualwarehouse/hive/resource_hive_vw_acc_test.go
resources/dw/virtualwarehouse/hive/resource_hive_vw_test.go
resources/dw/virtualwarehouse/hive/schema_hive_vw.go

To make the accpetance test generic the availability zone should be selected automatically. This way we can run the tests in different regions too, not only in us-west-2.

CDPCP-14163 The availability zone should be selected automatically

---

docs/resources/dw_vw_impala.md
examples/resources/cdp_dw_vw_impala/resource.tf
resources/dw/resource_dw_aws_acc_test.go
resources/dw/virtualwarehouse/impala/model_impala_vw.go
resources/dw/virtualwarehouse/impala/resource_impala_vw.go
resources/dw/virtualwarehouse/impala/resource_impala_vw_acc_test.go
resources/dw/virtualwarehouse/impala/resource_impala_vw_test.go
resources/dw/virtualwarehouse/impala/schema_impala_vw.go

This commit adds the Impala resource and adds all the remaining properties except for a config and a subset of Autoscaling group. Those two need changes in Impala APIs as such would make those changes and would come back and try to enable the code here.

DWX-19926: Add Impala properties

---

resources/environments/schema_freeipa.go

mark instance_count_by_group and multi_az as computed to not to get complain upon deployment finish in case they are not specified

CDPCP-14613 - mark instance_count_by_group and multi_az as computed

---

resources/datahub/schema_gcp_datahub.go

https://cloudera.atlassian.net/browse/CDPCP-15075
As reported in [ENGESC-30658](https://cloudera.atlassian.net/browse/ENGESC-30658), the customer was seeing the following error when trying to deploy a COD database:
```
Cannot use attr.Value basetypes.Int32Value, only basetypes.Int64Value is supported because basetypes.Int64Type is the type in the schema
```
This issue was fixed in [CDPCP-15056](https://cloudera.atlassian.net/browse/CDPCP-15056).  However, the customer then started seeing the following:
```
│ Error: Value Conversion Error
│
│ with cdp_datahub_gcp_cluster.cloudera_yarn_only_cluster,
│ on cloudera_environment.tf line 92, in resource "cdp_datahub_gcp_cluster" "cloudera_yarn_only_cluster":
│ 92: resource "cdp_datahub_gcp_cluster" "cloudera_yarn_only_cluster" {
│
│ An …
```

CDPCP-15075: Conversion issue for Int32 and Int64 types in datahub
